/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.junitandmockitoasahabit.view;

import com.junitandmockitoasahabit.controller.QuoteController;

/**
 *
 * @author AntonGolovin
 */
public class QuoteWindowView extends javax.swing.JFrame {

    private QuoteController controller; 
    
    /**
     * Creates new form QuoteWindowView
     */
    public QuoteWindowView() {
        try {
            this.controller = new QuoteController(this);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            System.exit(0);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quoteTextAreaScrollPane = new javax.swing.JScrollPane();
        quoteTextArea = new javax.swing.JTextArea();
        randomQuoteButton = new javax.swing.JButton();
        exitAppButton = new javax.swing.JButton();
        roundrobinQuoteButton = new javax.swing.JButton();
        resetQuotesButton = new javax.swing.JButton();
        quoteLocationWithinQuotesProgressBar = new javax.swing.JProgressBar();
        aboutButton = new javax.swing.JButton();
        appLogoImage = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GRG003JUnitAndMockitoAsAHabit (Not an Afterthought) App");
        setAlwaysOnTop(true);

        quoteTextArea.setEditable(false);
        quoteTextArea.setColumns(20);
        quoteTextArea.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        quoteTextArea.setLineWrap(true);
        quoteTextArea.setRows(5);
        quoteTextArea.setText("Check me out -->");
        quoteTextArea.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20))));
        quoteTextAreaScrollPane.setViewportView(quoteTextArea);

        randomQuoteButton.setText("Show Random Quote");
        randomQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomQuoteButtonActionPerformed(evt);
            }
        });

        exitAppButton.setText("Exit App");
        exitAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppButtonActionPerformed(evt);
            }
        });

        roundrobinQuoteButton.setText("Show RoundRobin Quote");
        roundrobinQuoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundrobinQuoteButtonActionPerformed(evt);
            }
        });

        resetQuotesButton.setText("Reset Quotes");
        resetQuotesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetQuotesButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout appLogoImageLayout = new javax.swing.GroupLayout(appLogoImage);
        appLogoImage.setLayout(appLogoImageLayout);
        appLogoImageLayout.setHorizontalGroup(
            appLogoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        appLogoImageLayout.setVerticalGroup(
            appLogoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quoteLocationWithinQuotesProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quoteTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(randomQuoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitAppButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roundrobinQuoteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(resetQuotesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appLogoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(aboutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(randomQuoteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundrobinQuoteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetQuotesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(appLogoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(aboutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitAppButton))
                    .addComponent(quoteTextAreaScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(quoteLocationWithinQuotesProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundrobinQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundrobinQuoteButtonActionPerformed
        this.controller.roundrobin();
    }//GEN-LAST:event_roundrobinQuoteButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        this.quoteTextArea.setText("GRG003JUnitAndMockitoAsAHabit Learning App...");
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void exitAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppButtonActionPerformed
        this.controller.stop();
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitAppButtonActionPerformed

    private void randomQuoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomQuoteButtonActionPerformed
         this.controller.random();
    }//GEN-LAST:event_randomQuoteButtonActionPerformed

    private void resetQuotesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetQuotesButtonActionPerformed
        this.controller.reset();
    }//GEN-LAST:event_resetQuotesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuoteWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuoteWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuoteWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuoteWindowView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuoteWindowView().setVisible(true);
            }
        });
    }
    
    public void setQuoteTextArea(String message) {
        quoteTextArea.setText(message);
    }
    
    public void setQuoteLocationWithinQuotesProgressBar(int min, int max, int value) {
        this.quoteLocationWithinQuotesProgressBar.setMinimum(min);
        this.quoteLocationWithinQuotesProgressBar.setMaximum(max);
        this.quoteLocationWithinQuotesProgressBar.setValue(value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel appLogoImage;
    private javax.swing.JButton exitAppButton;
    private javax.swing.JProgressBar quoteLocationWithinQuotesProgressBar;
    private javax.swing.JTextArea quoteTextArea;
    private javax.swing.JScrollPane quoteTextAreaScrollPane;
    private javax.swing.JButton randomQuoteButton;
    private javax.swing.JButton resetQuotesButton;
    private javax.swing.JButton roundrobinQuoteButton;
    // End of variables declaration//GEN-END:variables
}
